# Generated by Django 4.1.3 on 2022-12-06 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_tables_can_connect_tables_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='estimatedTimeTillCustomerLeaves',
        ),
    ]
