# Generated by Django 4.1.3 on 2022-12-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_delete_estimatedtimetillcustomerleaves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatedtimecustomersspend',
            name='number_of_people',
            field=models.IntegerField(),
        ),
    ]
