# Generated by Django 4.1.3 on 2022-12-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_alter_estimatedtimecustomersspend_number_of_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimatedtimecustomersspend',
            name='number_of_people',
        ),
        migrations.AddField(
            model_name='estimatedtimecustomersspend',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
