# Generated by Django 4.1.3 on 2022-12-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_remove_estimatedtimecustomersspend_number_of_people_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatedtimecustomersspend',
            name='number',
            field=models.FloatField(),
        ),
    ]
