# Generated by Django 4.1.3 on 2022-12-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_alter_estimatedtimecustomersspend_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatedtimecustomersspend',
            name='number',
            field=models.CharField(max_length=254),
        ),
    ]
