# Generated by Django 4.1.3 on 2022-12-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_alter_estimatedtimecustomersspend_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimatedtimecustomersspend',
            name='number',
        ),
        migrations.AddField(
            model_name='estimatedtimecustomersspend',
            name='number_of_people',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='numberofpeoplewhentablesconnect',
            name='number_of_chairs',
            field=models.IntegerField(),
        ),
    ]
