# Generated by Django 4.1.3 on 2022-12-16 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_remove_estimatedtimecustomersspend_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='limitOfCustomersPerHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekdays', models.CharField(max_length=254)),
                ('number_of_people', models.PositiveIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurantlimitcustomerperhour', to='restaurants.restaurants')),
            ],
        ),
    ]
