# Generated by Django 4.1.3 on 2022-12-16 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_limitofcustomersperhour'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitofcustomersperhour',
            name='each_time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
