# Generated by Django 4.1.3 on 2022-12-16 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_limitofcustomersperhour_each_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limitofcustomersperhour',
            name='each_time',
        ),
        migrations.AlterField(
            model_name='restaurantopendaysoftheweek',
            name='weekday',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=254),
        ),
        migrations.CreateModel(
            name='timeDivider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('each_time', models.CharField(choices=[('00:05', '00:05'), ('00:10', '00:10'), ('00:15', '00:15'), ('00:20', '00:20'), ('00:30', '00:30'), ('00:45', '00:45'), ('01:00', '01:00'), ('01:15', '01:15'), ('01:30', '01:30'), ('02:00', '02:00')], default='00:05', max_length=254)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restauranttimedivider', to='restaurants.restaurants')),
            ],
        ),
    ]
