# Generated by Django 4.1.3 on 2022-12-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_remove_limitofcustomersperhour_weekdays_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeoftable',
            name='place_of_table',
            field=models.CharField(max_length=254),
        ),
    ]
