# Generated by Django 4.1.3 on 2022-12-21 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_alter_placeoftable_place_of_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables',
            name='table_number',
            field=models.CharField(max_length=254),
        ),
    ]
