# Generated by Django 4.1.3 on 2022-12-06 15:38

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], default='Breakfast', max_length=254)),
                ('time', models.CharField(max_length=254)),
                ('estimatedtime', models.CharField(default='', max_length=254)),
                ('tablesused', models.CharField(default='', max_length=254)),
                ('number_of_people', models.PositiveIntegerField()),
                ('baby_chair', models.PositiveIntegerField()),
                ('message', models.CharField(max_length=254)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_of_reservation', to='restaurants.restaurants')),
                ('table_place_preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placeoftable', to='restaurants.placeoftable')),
            ],
        ),
    ]
